In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('global_startup_success_dataset.csv')
df.head()

,Startup Name,Founded Year,Country,Industry,Funding Stage,Total Funding ($M),Number of Employees,Annual Revenue ($M),Valuation ($B),Success Score,Acquired?,IPO?,Customer Base (Millions),Tech Stack,Social Media Followers
0,Startup_1,2009,Canada,Healthcare,Series A,269,3047,104,46.11,5,No,No,43,"Java, Spring",4158814
1,Startup_2,2004,UK,Healthcare,IPO,40,630,431,33.04,1,No,Yes,64,"Node.js, React",4063014
2,Startup_3,2018,USA,Healthcare,Seed,399,2475,375,15.79,8,No,No,74,"PHP, Laravel",3449855
3,Startup_4,2014,France,Tech,Seed,404,1011,907,17.12,7,Yes,Yes,26,"Python, AI",630421
4,Startup_5,2006,Japan,Energy,Series C,419,3917,280,4.39,6,Yes,Yes,30,"Node.js, React",365956

In [3]:
df.tail()

,Startup Name,Founded Year,Country,Industry,Funding Stage,Total Funding ($M),Number of Employees,Annual Revenue ($M),Valuation ($B),Success Score,Acquired?,IPO?,Customer Base (Millions),Tech Stack,Social Media Followers
4995,Startup_4996,2016,Canada,Healthcare,Seed,249,2378,84,3.79,6,Yes,No,96,"PHP, Laravel",3527296
4996,Startup_4997,2010,China,Tech,Series C,249,4235,578,0.90,8,No,No,55,"PHP, Laravel",4206134
4997,Startup_4998,2017,France,AI,Series A,336,2485,265,13.07,1,Yes,No,23,"Python, AI",1165258
4998,Startup_4999,2008,France,Energy,Series B,34,1734,35,46.62,6,Yes,No,75,"Java, Spring",4353149
4999,Startup_5000,2020,Germany,EdTech,Series A,280,2925,505,0.86,8,Yes,Yes,87,"C++, ML",917789

In [4]:
df.shape

(5000, 15)

In [5]:
df.columns

Index(['Startup Name', 'Founded Year', 'Country', 'Industry', 'Funding Stage',
       'Total Funding ($M)', 'Number of Employees', 'Annual Revenue ($M)',
       'Valuation ($B)', 'Success Score', 'Acquired?', 'IPO?',
       'Customer Base (Millions)', 'Tech Stack', 'Social Media Followers'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Startup Name              5000 non-null   object
 1   Founded Year              5000 non-null   int64
 2   Country                   5000 non-null   object
 3   Industry                  5000 non-null   object
 4   Funding Stage             5000 non-null   object
 5   Total Funding ($M)        5000 non-null   int64
 6   Number of Employees       5000 non-null   int64
 7   Annual Revenue ($M)       5000 non-null   int64
 8   Valuation ($B)            5000 non-null   float64
 9   Success Score             5000 non-null   int64
 10  Acquired?                 5000 non-null   object
 11  IPO?                      5000 non-null   object
 12  Customer Base (Millions)  5000 non-null   int64
 13  Tech Stack                5000 non-null   object
 14  Social Media Followers    5000 non-null   int64
dtypes: float64(1), int64(7), object(7)
memory usage: 586.1+ KB

In [7]:
df.describe()

,Founded Year,Total Funding ($M),Number of Employees,Annual Revenue ($M),Valuation ($B),Success Score,Customer Base (Millions),Social Media Followers
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,2010.960400,251.409400,2484.582800,495.721600,25.237284,4.965000,49.302800,2.560720e+06
std,6.628123,143.924874,1451.626957,290.071494,14.509278,2.574316,28.364894,1.430807e+06
min,2000.000000,1.000000,5.000000,1.000000,0.110000,1.000000,1.000000,1.005000e+03
25%,2005.000000,125.750000,1233.750000,240.750000,12.845000,3.000000,25.000000,1.353902e+06
50%,2011.000000,255.000000,2493.000000,496.000000,25.460000,5.000000,49.000000,2.618292e+06
75%,2017.000000,376.000000,3730.500000,746.000000,37.650000,7.000000,74.000000,3.802054e+06
max,2022.000000,499.000000,4998.000000,999.000000,49.980000,9.000000,99.000000,4.999860e+06

Explore Data

In [9]:
df.isnull().sum()

Startup Name                0
Founded Year                0
Country                     0
Industry                    0
Funding Stage               0
Total Funding ($M)          0
Number of Employees         0
Annual Revenue ($M)         0
Valuation ($B)              0
Success Score               0
Acquired?                   0
IPO?                        0
Customer Base (Millions)    0
Tech Stack                  0
Social Media Followers      0
dtype: int64

In [12]:
df['Number of Employees'].value_counts()

Number of Employees
3005    7
383     6
3625    6
2330    6
146     5
       ..
4126    1
991     1
1059    1
1322    1
2925    1
Name: count, Length: 3167, dtype: int64

In [ ]:
df.groupby('category_column')['numeric_column'].mean()